### ISSUE TITLE
Fix broken example in README.md

### ISSUE THREAD

**Issue by nermolov** [resin-io-modules/etcher-image-write#66]
Example in README.md does not work as the image input object is incorrectly loaded with ```fs.createWriteStream('my/image')``` instead of ```fs.createReadStream('my/image')```

Fixed emitter example:
```
var emitter = imageWrite.write({
  fd: fs.openSync('/dev/rdisk2', 'rs+'),
  device: '/dev/rdisk2',
  size: 2014314496
}, {
  stream: fs.createReadStream('my/image'),
  size: fs.statSync('my/image').size
}, {
  check: true
});
```

**Comment by jviotti** [comment]
Thanks a lot for the heads up! I've send a PR with the fix!
