### ISSUE TITLE
Doesn't work with Node 4 because of ES6 syntax

### ISSUE THREAD

**Issue by emirotin** [resin-io-modules/etcher-image-write#93]
This module is transitively used in the CLI. Node v4 does not support parts of the ES6 syntax (like default function arguments).

Can we please start _publishing_ this module in ES5 (and you can keep _importing_ it in ES6 in Etcher if you wish to by having an extra entry point, like `etcher-image-writer/es6`)

**Comment by jviotti** [comment]
Given that the CLI is the user facing program, I believe transpiling should be done on that side. We can publish every module that we have control of as ES6, but we might eventually hit another wall with other dependencies (there are more and more ES6 dependencies on the wild as far as I've seen). The problem should be solved 100% by transpiling on the CLI.

**Comment by emirotin** [comment]
I can't agree. Honestly I've never seen Node.js programs doing recursive transpilation of their dependencies. I don't even have any good idea how to do this, and it will definitely require more work.

**Comment by jviotti** [comment]
The thing is that enforcing every module in the dependency tree to support older versions is not the solution to the problem. We can mitigate it by converting the ones we control, but we'll have the same problem again sometime in the future.

By reading the resin.io TypeScript spec and the skeleton app, it looks like we're going to publish TypeScript straight away (see how the skeleton project points the `main` property of `package.json` to the TypeScript file: https://github.com/resin-io/resin-typescript-skeleton/blob/master/package.json#L6):

```json
{
    ...
    "main": "lib/index.ts",
    "types": "lib/index.d.ts",
    ...
}
```

The `package.json` does point the `start` script to the built code, which implies that only the top level applications will be transpiled. How are we going to deal with the problem in that case?

> I don't even have any good idea how to do this, and it will definitely require more work.

You can concatenate the JavaScript and do any transformations there, which is what we do on the Etcher CLI. Something like:

```sh
browserify entrypoint.js --node --outfile cli.js
```

should do it as long as there are no dynamic dependencies (we had an arch call that concluded that Webpack can resolve those).

Keep in mind that concatenation is something that we plan to do for our CLIs in any case (we are planning to move the Etcher CLI build system to Capitano, so we can distribute completely independent binary versions of our CLI, without having to rely on npm), so we should start going that way on the Resin CLI as well.

We rather deal with transpilation on particular projects that having to setup and deal with the whole infrastructure in every module IMHO.

**Comment by emirotin** [comment]
OK

**Comment by jviotti** [comment]
Turns out the only thing preventing this module from running on v4 was default arguments, which in most cases, it was useless. I removed them, so this module should run fine on v4 now.

**Comment by jviotti** [comment]
Check 9.0.3

**Comment by emirotin** [comment]
awesome 👍 . Will do by adding Node v4 tests to the downstream projects
